import type { NextConfig } from "next";
import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { resolve } from "path";

interface CommitInfo {
  sha: string;
  subject: string;
  date: string;
}

function gitRecent(n: number): CommitInfo[] {
  try {
    // \x1f = unit separator (between fields); \x1e = record separator (between commits)
    const out = execSync(
      `git log -${n} --format=%h%x1f%s%x1f%ci%x1e`,
      { stdio: ["ignore", "pipe", "ignore"] }
    ).toString();
    return out
      .split("\x1e")
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => {
        const [sha, subject, date] = line.split("\x1f");
        return { sha, subject, date };
      });
  } catch {
    return [];
  }
}

// Freeze the latest 3 commits into a TS module that code can import directly.
// This works identically in client bundle and server runtime — no env quirks.
// The file is overwritten on every build; git will show diffs but commits
// it anyway so IDE / dev-without-build imports keep compiling.
const commits = gitRecent(3);
const generatedPath = resolve(__dirname, "src/lib/build-info.generated.ts");
const generatedSource =
  `// AUTO-GENERATED by next.config.ts at build time. Do NOT edit by hand.\n` +
  `// The stub values here are placeholders for dev / pre-build imports; every\n` +
  `// \`next build\` overwrites this file with the real latest-3 commits.\n` +
  `export interface CommitInfo {\n  sha: string;\n  subject: string;\n  date: string;\n}\n\n` +
  `export const RECENT_COMMITS: CommitInfo[] = ${JSON.stringify(commits, null, 2)};\n`;
writeFileSync(generatedPath, generatedSource);

const nextConfig: NextConfig = {
  output: "standalone",
  serverExternalPackages: ["postgres"],
};

export default nextConfig;
