"use client";

import { useState, useEffect } from "react";
import { RECENT_COMMITS, type CommitInfo } from "@/lib/build-info.generated";

type Commit = CommitInfo;

interface UpdatesResp {
  commits: Commit[];
  summary?: string;
  expired?: boolean;
  fromCache?: boolean;
}

const BANNER_MAX_AGE_MS = 3 * 24 * 60 * 60 * 1000; // auto-hide after 3 days

// Build-time baked list. Imported directly so it's bundle-inlined on both
// client and server. Used as an early hint so the banner can hide before
// the API round-trip when commits are already stale.
const BAKED = RECENT_COMMITS;

function timeAgo(iso: string): string {
  const t = new Date(iso).getTime();
  if (!Number.isFinite(t)) return "";
  const diff = Date.now() - t;
  if (diff < 60_000) return "刚刚";
  const mins = Math.floor(diff / 60_000);
  if (mins < 60) return `${mins} 分钟前`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs} 小时前`;
  const days = Math.floor(hrs / 24);
  return `${days} 天前`;
}

function firstLine(text: string): string {
  const line = text.split(/\r?\n/).find((l) => l.trim());
  if (!line) return "";
  return line.replace(/^[·•\-*]\s*/, "").trim();
}

/**
 * Slim top banner summarizing the latest deployments. Summary text is
 * generated by the LLM via /api/updates (cached per commit-list). Stays
 * visible across page loads; auto-disappears when the newest commit is
 * older than 3 days. No dismiss button — the 3-day cutoff is the only
 * way the banner goes away.
 */
export default function UpdateBanner() {
  const [data, setData] = useState<UpdatesResp | null>(null);
  const [expanded, setExpanded] = useState(false);

  // Early hide: if the bundle-baked newest commit is already > 3 days old,
  // don't even hit the API.
  const earlyHide =
    BAKED.length === 0 ||
    (() => {
      const t = new Date(BAKED[0].date).getTime();
      return !Number.isFinite(t) || Date.now() - t > BANNER_MAX_AGE_MS;
    })();

  useEffect(() => {
    if (earlyHide) return;
    fetch("/api/updates")
      .then((r) => (r.ok ? r.json() : null))
      .then((json) => {
        if (json) setData(json);
      })
      .catch(() => {});
  }, [earlyHide]);

  if (earlyHide) return null;
  if (!data || data.expired || !data.commits?.length) return null;

  const newest = data.commits[0];
  const summary = (data.summary || "").trim();
  const headline = summary ? firstLine(summary) : newest.subject;

  return (
    <div
      className="fixed top-0 left-0 right-0 z-[60] bg-primary text-primary-content shadow-md"
      role="status"
    >
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        className="flex items-center gap-2 px-3 py-1.5 w-full text-xs text-left hover:bg-primary-content/5 transition-colors"
        aria-expanded={expanded}
      >
        <span className="font-semibold whitespace-nowrap">✨ 最近更新</span>
        <span className="flex-1 truncate">{headline}</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          strokeWidth={2.2}
          stroke="currentColor"
          className={`w-3 h-3 shrink-0 transition-transform ${expanded ? "rotate-180" : ""}`}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M6 9l6 6 6-6" />
        </svg>
      </button>
      {expanded && (
        <div className="px-3 pb-2 pt-1 text-xs border-t border-primary-content/20 space-y-1.5">
          {summary ? (
            <div className="whitespace-pre-wrap leading-relaxed">{summary}</div>
          ) : (
            <div className="opacity-70 italic">生成摘要中...</div>
          )}
          <details className="opacity-75">
            <summary className="cursor-pointer select-none outline-none">
              查看具体提交
            </summary>
            <ul className="mt-1 space-y-1">
              {data.commits.map((c) => (
                <li key={c.sha} className="flex gap-2 items-start py-0.5">
                  <code className="opacity-60 shrink-0 font-mono">{c.sha}</code>
                  <span className="flex-1 break-words">{c.subject}</span>
                  <span className="opacity-60 whitespace-nowrap shrink-0">
                    {timeAgo(c.date)}
                  </span>
                </li>
              ))}
            </ul>
          </details>
        </div>
      )}
    </div>
  );
}
