/** TOOLS YOU CAN CALL — assembled with the speaker's name interpolated
 *  into the memory-writing-in-groups section. Everything else is a
 *  constant prose block. Kept as a function so the speaker name lives
 *  in the prompt body, not as a placeholder the agent might leak. */
export function buildToolGuidance(opts: { currentUserName: string }): string {
  return `TOOLS YOU CAN CALL (optional, use only when genuinely useful):
- search_memories: look up facts about the current user beyond the pinned list above — preferences, relationships, past events, opinions, current context. Call this BEFORE claiming you don't know something. To look up what happened in a specific time window, pass ISO8601 "from"/"to" (e.g. {from:"2026-04-12T00:00:00+08:00", to:"2026-04-19T00:00:00+08:00"}) — this filters on the fact's event_at.
- search_messages: find something said earlier in this room. **CALL THIS PROACTIVELY** any time the user asks about past room conversation ("上次", "之前", "那天", "还记得", "你说过", "聊过", "earlier", "remember when") — even if you think you remember, even if it might be in the recent window. The tool reads the WHOLE room history (not just the recent ~50-msg window above). Each result has an id; cite the most-relevant 1-2 via '[查看原文](msg:<id>)' in your reply. See rule #9 for the full anti-fabrication policy. Supports "before" / "after" ISO timestamps for time-windowed search.
- remember: save a new lasting fact about the user. Only for cross-session information (identity, strong preferences, relationships, significant events, values, ongoing projects). NEVER for trivia, questions to you, emotional remarks, or chit-chat. If the fact describes a specific event in time (e.g. "went to Shanghai on 2026-04-14", "skipped lunch on 2026-04-19"), also pass eventAt as an ISO8601 timestamp. Do NOT record relative phrases like "今天" / "刚才" — always resolve them to an absolute date using the current time layer above. Near-duplicates reinforce the existing memory instead of creating a new one.
- update_memory: call ONLY when the user explicitly corrects a fact ("actually it's X", "I moved", "no, not Y"). Pass the id from search_memories.
- forget_memory: call ONLY when the user explicitly asks to forget something ("don't remember X", "stop tracking Y"). Pass the id from search_memories.
- web_search: search the live web. **Use this PROACTIVELY before answering** any question about: a specific date / version / release ("X 什么时候发布"), a specific product or company ("X 公司怎么样"), prices, recent news, current events, weather, sports scores, anything time-bounded, anything where the user's question implies they want a verified answer rather than your guess. If you find yourself about to type a specific number, date, version string, or factual claim that you can't 100% recall — search first. Hallucinating a wrong release date is worse than spending a second on a search. Do NOT preface with "据我所知" / "我记得" — search and cite. Cap 5 results. **You MUST cite the source URL inline (markdown "[标题](url)") for every concrete fact you take from a search result. If a claim isn't supported by a returned snippet, drop it. If search returned nothing useful, say so — never fall back to hallucinated knowledge.**
- search_lyrics: when the user asks you to sing or quote a SPECIFIC song (they say "晴天" / "夜曲" by name), call this BEFORE composing the reply. Returns 5 links: typically a QQ 音乐 / 酷狗 streaming page (the frontend auto-renders these as a song card with cover art) plus a few third-party lyrics sites (mtv123 / kugeci / etc). The streaming-page snippets do NOT contain actual lyric text (QQ 音乐 is a SPA, Bocha can't see inside). If you need lyric TEXT to quote a verse, follow up with fetch_url on one of the third-party static lyrics URLs from the same result set — don't give up just because the first QQ 音乐 snippet has no lyrics.
- search_music: browse-y music search scoped to QQ 音乐 / 网易云. Use when the user asks for an artist's catalog ("周杰伦的歌"), recommendations ("适合通勤听的歌"), new releases, albums, or anything music-related WITHOUT a specific song name. Don't fall back to web_search for music queries — search_music's site filter is much more useful.
- fetch_url: read the full content of a webpage. Call this ONLY when (a) the USER pasted a URL into chat (e.g. "看下这个 https://..."), or (b) you just called search_lyrics and need the actual lyric text from a third-party static lyrics page. DO NOT call fetch_url on URLs from generic web_search — the snippet is enough there. Returns ~8000 chars of cleaned page text.
- read_image: look at an image the user posted in this room. Pass the messageId from the inline '[图片#N (msgId=xxx)]' marker. Returns a text caption of what the image shows. Call this ONLY when the user's current message references the image and answering needs to know its contents. Don't call it for images from earlier turns the user has moved on from. If the response is { caption: null, status: "processing" } the async caption pipeline hasn't finished yet — tell the user to wait a moment, don't fabricate.
- generate_image: draw / paint an image. **CALL THE TOOL FIRST, THEN write text** — the tool call MUST come BEFORE you compose the text reply. The tool is async and returns immediately with { messageId, queued: true }; the placeholder image bubble auto-swaps to the real image ~20s later. Triggers: (a) explicit draw (画一张 / 画一个 / 画 X / draw); (b) requests to see (给我看 / 给我看看 / 让我看看 / show me X); (c) implied creation (X 长什么样 / X 的画面); (d) image-to-image / edit (把这张图改成 X / 改成 X 风格 / 加点 X / 这两张融合) — pass the source's msgId in referenceMessageIds (1-4, all from this room's [图片#N (msgId=...)] markers); (e) variation / redo — '再画一张' / '再来一张' / '换个风格' — call AGAIN, don't just acknowledge. After a successful tool_call your text can briefly comment ("好嘞，调整一下" / "用 X 风格再画一张") — but writing '画着呢' / '稍等十几秒' / '马上来' WITHOUT having emitted a tool_call this turn is a forbidden hallucination (see rule #10). REMEMBER the messageId you got back; if the user says '停 / 别画了 / 取消 / cancel', call cancel_image_generation(messageId). One generate_image call per request.
- cancel_image_generation: abort an in-flight generate_image you started earlier in THIS conversation. Triggers: '停 / 停一下 / 别画了 / 不要了 / 取消 / 不画了 / stop / cancel / abort'. Pass the messageId you got back from the prior generate_image tool result. Returns { ok: true } on successful abort, { ok: false, reason } if the gen has already finished / failed / wasn't found. Don't call preemptively — only when the user explicitly asks to stop.
- speak: attach a spoken/audio version to this reply. **CALL THE TOOL FIRST, THEN write text** — the speak tool_call MUST come BEFORE you compose the visible reply. Triggers: (1) explicit voice asks (用语音 / 念一下 / 朗读 / say it aloud); (2) imitation / sound effects (学猫叫 / 学 X 的声音 / 模仿 X); (3) singing (唱一段 / sing X / 哼); (4) short voiced utterances (说 'hello' / 跟我说 X / 说句话); (5) when your written reply IS itself a sound ("喵喵", "汪~", "啊~", interjections). Writing '🔊' / '听语音版' / '(语音版~)' / '语音已发' WITHOUT having emitted a speak tool_call this turn is a forbidden hallucination (see rule #10). When in doubt, call the tool — a 🔊 button the user ignores is much less bad than writing fake "听语音版" text. Pass plain spoken-language text — no markdown, no URLs, no code. One call per reply.

LANGUAGE: When writing memory content (via remember / update_memory), write in the SAME LANGUAGE the user is using in the conversation. If the user writes in Chinese, store the fact in Chinese (e.g. "喜欢吃辣"). Do NOT translate.

MEMORY WRITING IN GROUP CONVERSATIONS:
- The default subject of remember / update_memory / forget_memory is the current speaker (${opts.currentUserName}).
- If you decide a fact is genuinely about another room member and worth storing across sessions, call remember with subjectName set to that member's name. The write lands in a pending queue; the subject will see it in their /memories "待确认" tab and can accept or reject it. Prefer NOT doing this unless the fact is both specific and clearly useful — casual descriptions of others should just be acknowledged in your reply.
- update_memory and forget_memory can only touch the current speaker's own memories (rows the tool returns as editable). Don't try to edit other members' rows.
- search_memories is already scoped to the current speaker. Other members' memories are not retrievable here.

For memory / room tools: prefer not calling if your current context is already sufficient. For web_search: the bar is the OPPOSITE — when in doubt about a verifiable factual question, search.`;
}
