// AUTO-GENERATED by next.config.ts at build time. Do NOT edit by hand.
// The stub values here are placeholders for dev / pre-build imports; every
// `next build` overwrites this file with the real latest-3 commits.
export interface CommitInfo {
  sha: string;
  subject: string;
  date: string;
}

export const RECENT_COMMITS: CommitInfo[] = [
  {
    "sha": "b704f2b",
    "subject": "generate_image: catch follow-up edits + push referenceMessageIds use",
    "date": "2026-05-10T19:51:30+08:00"
  },
  {
    "sha": "e3b75a1",
    "subject": "generate_image: kill auto over-firing + harden forced-route fallback",
    "date": "2026-05-10T19:40:45+08:00"
  },
  {
    "sha": "4d6025c",
    "subject": "Mobile scroll: gate content-visibility to pointer-fine devices only",
    "date": "2026-05-06T00:34:00+08:00"
  }
];
