// AUTO-GENERATED by next.config.ts at build time. Do NOT edit by hand.
// The stub values here are placeholders for dev / pre-build imports; every
// `next build` overwrites this file with the real latest-3 commits.
export interface CommitInfo {
  sha: string;
  subject: string;
  date: string;
}

export const RECENT_COMMITS: CommitInfo[] = [
  {
    "sha": "96474d6",
    "subject": "Move version-update notice from fixed banner to sidebar announcement",
    "date": "2026-04-18T08:51:52+08:00"
  },
  {
    "sha": "d020b0d",
    "subject": "Make /api/updates public so the banner reaches anonymous visitors",
    "date": "2026-04-18T08:44:50+08:00"
  },
  {
    "sha": "52dd111",
    "subject": "Fix banner: bake commits into a TS module instead of NEXT_PUBLIC env",
    "date": "2026-04-18T08:05:51+08:00"
  }
];
