// AUTO-GENERATED by next.config.ts at build time. Do NOT edit by hand.
// The stub values here are placeholders for dev / pre-build imports; every
// `next build` overwrites this file with the real latest-3 commits.
export interface CommitInfo {
  sha: string;
  subject: string;
  date: string;
}

export const RECENT_COMMITS: CommitInfo[] = [
  {
    "sha": "5befb2f",
    "subject": "Memory Phase α Reflection v1: event cluster → 高阶模式",
    "date": "2026-05-18T21:21:06+08:00"
  },
  {
    "sha": "ab975f6",
    "subject": "Memory Phase α M5c+M5d: cosine dedup + search_memories cosine top-up",
    "date": "2026-05-18T20:09:58+08:00"
  },
  {
    "sha": "b0b059f",
    "subject": "Memory Phase α M5b: agent_memories embedding — backfill + 在线写",
    "date": "2026-05-18T20:00:45+08:00"
  }
];
